Symbol error
cloudteam2016/kubernetes.github.io pull request #2
Opened 2016-12-22 07:17 UTC by tim-zju

symbol errors in quotation mark( change “” to "" , ‘’ to '')

2016-12-22 09:48 UTC, xulike666 requested changes
please make sure all of changes are correct.

2016-12-22 09:48 UTC, xulike666 commented on _includes/partner-script.js
>  			type: 0,
What's this and please revert it.

2016-12-22 09:48 UTC, xulike666 commented on docs/getting-started-guides/meanstack.md
> +Le's build.
please revert this.

2016-12-22 10:19 UTC, tim-zju commented on docs/getting-started-guides/meanstack.md
> +Le's build.
ok, i have revert this opertion

2016-12-22 10:19 UTC, tim-zju commented on _includes/partner-script.js
>  			type: 0,
ok, i have revert this opertion

2016-12-22 10:25 UTC, xulike666 requested changes
Please make sure that do not change the default markdown format.

2016-12-22 10:25 UTC, xulike666 commented on docs/user-guide/managing-deployments.md
> +(print each resource as resource/name). Then we `grep` only the "service", and then print it with `kubectl get`.
Please do not change the default markdown format such as adding an unnoticed short blank at the end of line.

2016-12-22 12:33 UTC, tim-zju commented on docs/user-guide/managing-deployments.md
> +(print each resource as resource/name). Then we `grep` only the "service", and then print it with `kubectl get`.
i fixed these problems

2016-12-23 03:39 UTC, xulike666 approved these changes

2016-12-23 03:40 UTC, xulike666 commented
LGTM

2016-12-23 03:41 UTC, merged